#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get -y install nginx


mkdir -p /var/www/root/html

echo "Hello World!" > /var/www/root/html/index.html
echo "server {
              listen 80 default_server;
              listen [::]:80 default_server;

              root /var/www/root/html;
              index index.html index.htm;

              location / {
                      try_files $ur1 $uri/ =404;
              }
      }" > /etc/nginx/sites-available/default

service nginx restart
