#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get -y install nginx

echo "server {
              listen 80;
	      listen [::}:80;

	      root /var/www/html;
	      index index.html

	      location / {
	              echo 'Hello World!'
	      }
      }" > /etc/nginx/sites-available/default

service nginx restart
