#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get -y install nginx


echo "Hello World!" > /var/www/html/index.html
echo "server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              index index.html index.htm;
              location / {
                      try_files $uri $uri/ =404;
              }

service nginx restart
