#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
replacement_string="server_name _;\n\tlocation \/redirect_me {\n\treturn 301 https:\/\/dev.to\/thegirlsynth;\n\t}"
sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default

service nginx restart
