#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Getting a the server name and creating a replacement string
server_name=$(hostname)

replacement_string="server_name _;\
	\n\tadd_header X-Served-By '${server_name}';\
	\n\terror_page 404 \/404.html;\
	\n\tlocation \/redirect_me {\
	\n\treturn 301 https:\/\/dev.to\/thegirlsynth;\
	\n\t}"

# Replace server_name _ with replacement string in config file
sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default

service nginx restart
