#!/usr/bin/env bash
#Installs HAProxy on load balancer

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
config=\
"
frontend http
	bind *:80
	mode http
	default_backend new-backend
backend new-backend
	balance roundrobin
	server 63593-web-01 54.237.34.168:80 check
	server 63593-web-02 54.157.167.193:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Ensures HAProxy can be managed via an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
service haproxy restart
