#!/usr/bin/env bash
#Installs HAproxy on load balancer

apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0\*

#Ensures HAProxy can be managed via an init script
echo "ENABLED=1" | tee -a  /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

#Configure a proxy; add a frontend
config=\
"
frontend http
	mode http
        bind *:80
        default_backend new-backend
backend new-backend
        balance roundrobin
        server 63593-web-01 54.237.34.16:80 check
        server 63593-web-02 54.157.167.193:80 check
"
echo "$config" | tee -a /etc/haproxy/haproxy.cfg

#Restart HAProxy
service haproxy restart
