#!/usr/bin/env bash
# Generates a MySQL dump of all databases and creates a compressed archive out of it
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$(date +%d-%m-%Y)".tar.gz backup.sql
