#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely, with a 2s sleep between
# shellcheck disable=SC2009

list=1
while [ $list -le 1 ]; do
    echo "To infinity and beyond"
    sleep 2
done    
