#!/usr/bin/env bash
# This bash script displays the string, "Best School", 10 times.
#+ But for the 9th iteration, displays "Best School" and then "Hi" on a new line

var=10
while [ $var -ge 1 ]; do
	echo "Best School"
	if [ $var -eq 2 ]
	then
		echo "Hi"
	fi
	((var--))
done
