#!/usr/bin/env bash
# This bash script loops from 1 to 10 and:
#+ displays "bad luck" for the 4th loop iteration
#+ displays "good luck" for the 8th loop iteration
#+ displays "Best School" for the other iterations

var=10
while [ $var -ge 1 ]; do
	if [ $var -eq 7 ]
	then
		echo "bad luck"
	elif [ $var -eq 3 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((var--))
done
