#!/usr/bin/env bash
# This bash script displays the string, "Best School", 10 times.
#+ But for the 9th iteration, displays "Best School" and then "Hi" on a new line

var=10
while [ $var -ge 1 ]; do
	if [ $var -eq 7 ]
	then
		echo "bad luck"
	elif [ $var -eq 3 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((var--))
done
