#!/usr/bin/env bash
# This bash script displays numbers from 1 to 20 and:
#+ displays 4 and then "bad luck from China" for the 4th loop iteration
#+ displays 9 and then "bad luck from Japan" for the 9th loop iteration
#+ displays 17 and then "bad luck from Italy" for the 17th loop iteration


var=1
while [ $var -le 20 ]; do
	echo "$var"
	case "$var" in
		#case 1
		4) echo "bad luck from China" ;;
		#case 2
		9) echo "bad luck from Japan" ;;
		#case 3
		17) echo "bad luck from Italy" ;;
	esac
	((var++))
done
