#!/usr/bin/env bash
# This bash script displays the content of the current directory in a list format
#+ where only the part of the name after the first dash is displayed.

LIST=$(ls)
for i in $LIST; do
	cut -d '-' -f2 <(echo "$i" )
done
