#!/usr/bin/env bash
# Creates an RSA key pair
# Requirements:
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty

key_name="school"
bits_num=4096

ssh-keygen -t rsa -b $bits_num -f $key_name -N "betty"
